spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:./data/nutrition-calc-dev;AUTO_SERVER=FALSE;DATABASE_TO_UPPER=FALSE'
    username: 'sa'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  file:
    path: ./logs
  logback:
    rollingpolicy:
      max-file-size: 2MB
      max-history: 100