spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: 'jdbc:mariadb://lullaby.sldb.iwinv.net:3306/nutrition_calc_dev?serverTimezone=UTC&characterEncoding=UTF-8'
    username: 'nutrition-calc-dev'
    password: 'nutrition-calc-dev!@#'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

